name: Run Chromatic

on:
  push:
    branches:
      - "!master"

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      working-directory: omui
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Publish Storybook
        run: |
          yarn install
          yarn run chromatic --project-token=${{ secrets.CHROMATIC_PROJECT_TOKEN }} -b storybook:build --exit-zero-on-changes --exit-once-uploaded --skip 'dependabot/**'
        working-directory: ${{ env.working-directory }}

